spring:
  datasource:
    initialization-mode: always
    url: jdbc:h2:mem:test
    driverClassName: org.h2.Driver
    username: sa
    password:
  h2.console.enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    

